const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const dotenv = require("dotenv");
const path = require("path");

dotenv.config({ path: path.join(__dirname, "..", ".env") });

const User = require("../models/User");
const Team = require("../models/Team");
const Driver = require("../models/Driver");
const Race = require("../models/Race");
const Standing = require("../models/Standing");
const TeamStaff = require("../models/TeamStaff");
const RaceHistory = require("../models/RaceHistory");

const connectDB = async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log("MongoDB connected for seeding");
};

// ========== TEAMS 2026 ==========
const teamsData = [
  {
    name: "Red Bull Racing",
    fullName: "Oracle Red Bull Racing",
    base: "Milton Keynes, United Kingdom",
    teamPrincipal: "Christian Horner",
    powerUnit: "Ford",
    chassis: "RB22",
    firstEntry: 2005,
    worldChampionships: 6,
    color: "#3671C6",
  },
  {
    name: "Mercedes",
    fullName: "Mercedes-AMG PETRONAS F1 Team",
    base: "Brackley, United Kingdom",
    teamPrincipal: "Toto Wolff",
    powerUnit: "Mercedes",
    chassis: "W17",
    firstEntry: 2010,
    worldChampionships: 8,
    color: "#27F4D2",
  },
  {
    name: "Ferrari",
    fullName: "Scuderia Ferrari HP",
    base: "Maranello, Italy",
    teamPrincipal: "Frederic Vasseur",
    powerUnit: "Ferrari",
    chassis: "SF-26",
    firstEntry: 1950,
    worldChampionships: 16,
    color: "#E8002D",
  },
  {
    name: "McLaren",
    fullName: "McLaren F1 Team",
    base: "Woking, United Kingdom",
    teamPrincipal: "Andrea Stella",
    powerUnit: "Mercedes",
    chassis: "MCL60",
    firstEntry: 1966,
    worldChampionships: 8,
    color: "#FF8000",
  },
  {
    name: "Aston Martin",
    fullName: "Aston Martin Aramco F1 Team",
    base: "Silverstone, United Kingdom",
    teamPrincipal: "Andy Cowell",
    powerUnit: "Honda",
    chassis: "AMR26",
    firstEntry: 2021,
    worldChampionships: 0,
    color: "#229971",
  },
  {
    name: "Alpine",
    fullName: "BWT Alpine F1 Team",
    base: "Enstone, United Kingdom",
    teamPrincipal: "Oliver Oakes",
    powerUnit: "Mercedes",
    chassis: "A526",
    firstEntry: 2021,
    worldChampionships: 0,
    color: "#FF87BC",
  },
  {
    name: "Williams",
    fullName: "Williams Racing",
    base: "Grove, United Kingdom",
    teamPrincipal: "James Vowles",
    powerUnit: "Mercedes",
    chassis: "FW47",
    firstEntry: 1978,
    worldChampionships: 9,
    color: "#64C4FF",
  },
  {
    name: "RB",
    fullName: "Visa Cash App RB F1 Team",
    base: "Faenza, Italy",
    teamPrincipal: "Laurent Mekies",
    powerUnit: "Ford",
    chassis: "VCARB 02",
    firstEntry: 2024,
    worldChampionships: 0,
    color: "#6692FF",
  },
  {
    name: "Kick Sauber",
    fullName: "Stake F1 Team Kick Sauber",
    base: "Hinwil, Switzerland",
    teamPrincipal: "Mattia Binotto",
    powerUnit: "Ferrari",
    chassis: "C45",
    firstEntry: 1993,
    worldChampionships: 0,
    color: "#52E252",
  },
  {
    name: "Haas",
    fullName: "MoneyGram Haas F1 Team",
    base: "Kannapolis, United States",
    teamPrincipal: "Ayao Komatsu",
    powerUnit: "Ferrari",
    chassis: "VF-26",
    firstEntry: 2016,
    worldChampionships: 0,
    color: "#B6BABD",
  },
];

// ========== DRIVERS 2026 ==========
const driversData = [
  {
    firstName: "Max",
    lastName: "Verstappen",
    number: 1,
    nationality: "Dutch",
    dateOfBirth: "1997-09-30",
    teamName: "Red Bull Racing",
    worldChampionships: 4,
    totalRaceWins: 63,
    totalPodiums: 111,
    totalPoints: 2998,
    seasonsActive: "2015-present",
    biography:
      "Max Emilian Verstappen is a Dutch racing driver who competes in Formula One for Red Bull Racing. He is a four-time World Champion, winning consecutive titles from 2021 to 2024. Known for his aggressive driving style and exceptional racecraft.",
    history: [
      {
        year: 2024,
        team: "Red Bull Racing",
        position: 1,
        wins: 9,
        podiums: 14,
        points: 437,
      },
      {
        year: 2023,
        team: "Red Bull Racing",
        position: 1,
        wins: 19,
        podiums: 21,
        points: 575,
      },
      {
        year: 2022,
        team: "Red Bull Racing",
        position: 1,
        wins: 15,
        podiums: 17,
        points: 454,
      },
      {
        year: 2021,
        team: "Red Bull Racing",
        position: 1,
        wins: 10,
        podiums: 18,
        points: 395.5,
      },
      {
        year: 2020,
        team: "Red Bull Racing",
        position: 3,
        wins: 2,
        podiums: 11,
        points: 214,
      },
      {
        year: 2019,
        team: "Red Bull Racing",
        position: 3,
        wins: 3,
        podiums: 9,
        points: 278,
      },
      {
        year: 2018,
        team: "Red Bull Racing",
        position: 4,
        wins: 2,
        podiums: 11,
        points: 249,
      },
      {
        year: 2017,
        team: "Red Bull Racing",
        position: 6,
        wins: 2,
        podiums: 4,
        points: 168,
      },
      {
        year: 2016,
        team: "Red Bull Racing",
        position: 5,
        wins: 1,
        podiums: 7,
        points: 204,
      },
    ],
  },
  {
    firstName: "Liam",
    lastName: "Lawson",
    number: 30,
    nationality: "New Zealander",
    dateOfBirth: "2002-02-11",
    teamName: "Red Bull Racing",
    worldChampionships: 0,
    totalRaceWins: 0,
    totalPodiums: 0,
    totalPoints: 14,
    seasonsActive: "2024-present",
    biography:
      "Liam Lawson is a New Zealand racing driver who competes for Red Bull Racing in Formula One. After impressive stints as a substitute driver, he earned a full-time seat alongside Max Verstappen for 2026.",
    history: [
      { year: 2024, team: "RB", position: 16, wins: 0, podiums: 0, points: 14 },
    ],
  },
  {
    firstName: "Lewis",
    lastName: "Hamilton",
    number: 44,
    nationality: "British",
    dateOfBirth: "1985-01-07",
    teamName: "Ferrari",
    worldChampionships: 7,
    totalRaceWins: 105,
    totalPodiums: 202,
    totalPoints: 4829,
    seasonsActive: "2007-present",
    biography:
      "Sir Lewis Carl Davidson Hamilton is a British racing driver who competes in Formula One for Scuderia Ferrari. A seven-time World Champion, he holds records for most wins, pole positions, and podium finishes in F1 history.",
    history: [
      {
        year: 2024,
        team: "Mercedes",
        position: 7,
        wins: 2,
        podiums: 3,
        points: 211,
      },
      {
        year: 2023,
        team: "Mercedes",
        position: 3,
        wins: 0,
        podiums: 6,
        points: 234,
      },
      {
        year: 2022,
        team: "Mercedes",
        position: 6,
        wins: 0,
        podiums: 9,
        points: 240,
      },
      {
        year: 2021,
        team: "Mercedes",
        position: 2,
        wins: 8,
        podiums: 17,
        points: 387.5,
      },
      {
        year: 2020,
        team: "Mercedes",
        position: 1,
        wins: 11,
        podiums: 14,
        points: 347,
      },
      {
        year: 2019,
        team: "Mercedes",
        position: 1,
        wins: 11,
        podiums: 17,
        points: 413,
      },
      {
        year: 2018,
        team: "Mercedes",
        position: 1,
        wins: 11,
        podiums: 17,
        points: 408,
      },
      {
        year: 2017,
        team: "Mercedes",
        position: 1,
        wins: 9,
        podiums: 13,
        points: 363,
      },
      {
        year: 2016,
        team: "Mercedes",
        position: 2,
        wins: 10,
        podiums: 17,
        points: 380,
      },
    ],
  },
  {
    firstName: "Charles",
    lastName: "Leclerc",
    number: 16,
    nationality: "Monegasque",
    dateOfBirth: "1997-10-16",
    teamName: "Ferrari",
    worldChampionships: 0,
    totalRaceWins: 8,
    totalPodiums: 40,
    totalPoints: 1426,
    seasonsActive: "2018-present",
    biography:
      "Charles Marc Hervé Perceval Leclerc is a Monegasque racing driver competing for Ferrari in Formula One. Known for his qualifying prowess and aggressive racing, Leclerc is considered one of the most talented drivers of his generation.",
    history: [
      {
        year: 2024,
        team: "Ferrari",
        position: 3,
        wins: 3,
        podiums: 9,
        points: 356,
      },
      {
        year: 2023,
        team: "Ferrari",
        position: 7,
        wins: 0,
        podiums: 4,
        points: 206,
      },
      {
        year: 2022,
        team: "Ferrari",
        position: 2,
        wins: 3,
        podiums: 11,
        points: 308,
      },
      {
        year: 2021,
        team: "Ferrari",
        position: 7,
        wins: 0,
        podiums: 1,
        points: 159,
      },
      {
        year: 2020,
        team: "Ferrari",
        position: 8,
        wins: 0,
        podiums: 2,
        points: 98,
      },
      {
        year: 2019,
        team: "Ferrari",
        position: 4,
        wins: 2,
        podiums: 10,
        points: 264,
      },
      {
        year: 2018,
        team: "Sauber",
        position: 13,
        wins: 0,
        podiums: 0,
        points: 39,
      },
    ],
  },
  {
    firstName: "Lando",
    lastName: "Norris",
    number: 4,
    nationality: "British",
    dateOfBirth: "1999-11-13",
    teamName: "McLaren",
    worldChampionships: 0,
    totalRaceWins: 4,
    totalPodiums: 31,
    totalPoints: 1155,
    seasonsActive: "2019-present",
    biography:
      "Lando Norris is a British racing driver who competes for McLaren in Formula One. Known for his consistent performances and engaging personality, Norris has established himself as a leading contender in the sport.",
    history: [
      {
        year: 2024,
        team: "McLaren",
        position: 2,
        wins: 4,
        podiums: 12,
        points: 374,
      },
      {
        year: 2023,
        team: "McLaren",
        position: 6,
        wins: 0,
        podiums: 7,
        points: 205,
      },
      {
        year: 2022,
        team: "McLaren",
        position: 7,
        wins: 0,
        podiums: 0,
        points: 122,
      },
      {
        year: 2021,
        team: "McLaren",
        position: 6,
        wins: 0,
        podiums: 4,
        points: 160,
      },
      {
        year: 2020,
        team: "McLaren",
        position: 9,
        wins: 0,
        podiums: 1,
        points: 97,
      },
      {
        year: 2019,
        team: "McLaren",
        position: 11,
        wins: 0,
        podiums: 0,
        points: 49,
      },
    ],
  },
  {
    firstName: "Oscar",
    lastName: "Piastri",
    number: 81,
    nationality: "Australian",
    dateOfBirth: "2001-04-06",
    teamName: "McLaren",
    worldChampionships: 0,
    totalRaceWins: 2,
    totalPodiums: 10,
    totalPoints: 409,
    seasonsActive: "2023-present",
    biography:
      "Oscar Jack Piastri is an Australian racing driver competing for McLaren in Formula One. The 2021 F2 champion impressed immediately in F1 and secured his maiden victory in the 2024 Hungarian Grand Prix.",
    history: [
      {
        year: 2024,
        team: "McLaren",
        position: 4,
        wins: 2,
        podiums: 8,
        points: 292,
      },
      {
        year: 2023,
        team: "McLaren",
        position: 8,
        wins: 0,
        podiums: 2,
        points: 97,
      },
    ],
  },
  {
    firstName: "George",
    lastName: "Russell",
    number: 63,
    nationality: "British",
    dateOfBirth: "1998-02-15",
    teamName: "Mercedes",
    worldChampionships: 0,
    totalRaceWins: 3,
    totalPodiums: 18,
    totalPoints: 699,
    seasonsActive: "2019-present",
    biography:
      'George William Russell is a British racing driver competing for Mercedes in Formula One. Known as "Mr. Saturday" for his qualifying prowess, Russell has steadily risen through the ranks to become a race winner.',
    history: [
      {
        year: 2024,
        team: "Mercedes",
        position: 6,
        wins: 2,
        podiums: 5,
        points: 245,
      },
      {
        year: 2023,
        team: "Mercedes",
        position: 8,
        wins: 0,
        podiums: 2,
        points: 175,
      },
      {
        year: 2022,
        team: "Mercedes",
        position: 4,
        wins: 1,
        podiums: 8,
        points: 275,
      },
      {
        year: 2021,
        team: "Williams",
        position: 15,
        wins: 0,
        podiums: 0,
        points: 16,
      },
      {
        year: 2020,
        team: "Williams",
        position: 18,
        wins: 0,
        podiums: 0,
        points: 3,
      },
      {
        year: 2019,
        team: "Williams",
        position: 20,
        wins: 0,
        podiums: 0,
        points: 0,
      },
    ],
  },
  {
    firstName: "Kimi",
    lastName: "Antonelli",
    number: 12,
    nationality: "Italian",
    dateOfBirth: "2006-08-25",
    teamName: "Mercedes",
    worldChampionships: 0,
    totalRaceWins: 0,
    totalPodiums: 0,
    totalPoints: 0,
    seasonsActive: "2025-present",
    biography:
      "Andrea Kimi Antonelli is an Italian racing driver who joined Mercedes for 2025. A prodigious talent from the Mercedes junior programme, he won the 2024 F2 championship and is the youngest F1 driver in decades.",
    history: [],
  },
  {
    firstName: "Fernando",
    lastName: "Alonso",
    number: 14,
    nationality: "Spanish",
    dateOfBirth: "1981-07-29",
    teamName: "Aston Martin",
    worldChampionships: 2,
    totalRaceWins: 32,
    totalPodiums: 106,
    totalPoints: 2329,
    seasonsActive: "2001-2018, 2021-present",
    biography:
      "Fernando Alonso Díaz is a Spanish racing driver competing for Aston Martin. A two-time World Champion (2005, 2006), he is one of the most experienced and skilled drivers in F1 history.",
    history: [
      {
        year: 2024,
        team: "Aston Martin",
        position: 9,
        wins: 0,
        podiums: 0,
        points: 70,
      },
      {
        year: 2023,
        team: "Aston Martin",
        position: 4,
        wins: 0,
        podiums: 8,
        points: 206,
      },
      {
        year: 2022,
        team: "Alpine",
        position: 9,
        wins: 0,
        podiums: 0,
        points: 81,
      },
      {
        year: 2021,
        team: "Alpine",
        position: 10,
        wins: 0,
        podiums: 1,
        points: 81,
      },
      {
        year: 2018,
        team: "McLaren",
        position: 11,
        wins: 0,
        podiums: 0,
        points: 50,
      },
      {
        year: 2017,
        team: "McLaren",
        position: 15,
        wins: 0,
        podiums: 0,
        points: 17,
      },
      {
        year: 2016,
        team: "McLaren",
        position: 10,
        wins: 0,
        podiums: 0,
        points: 54,
      },
    ],
  },
  {
    firstName: "Lance",
    lastName: "Stroll",
    number: 18,
    nationality: "Canadian",
    dateOfBirth: "1998-10-29",
    teamName: "Aston Martin",
    worldChampionships: 0,
    totalRaceWins: 0,
    totalPodiums: 3,
    totalPoints: 292,
    seasonsActive: "2017-present",
    biography:
      "Lance Stroll is a Canadian racing driver competing for Aston Martin in Formula One. The son of team owner Lawrence Stroll, he became the youngest front-row starter in F1 at the time of his debut podium.",
    history: [
      {
        year: 2024,
        team: "Aston Martin",
        position: 13,
        wins: 0,
        podiums: 0,
        points: 24,
      },
      {
        year: 2023,
        team: "Aston Martin",
        position: 10,
        wins: 0,
        podiums: 1,
        points: 74,
      },
      {
        year: 2022,
        team: "Aston Martin",
        position: 15,
        wins: 0,
        podiums: 0,
        points: 18,
      },
      {
        year: 2021,
        team: "Aston Martin",
        position: 13,
        wins: 0,
        podiums: 0,
        points: 34,
      },
      {
        year: 2020,
        team: "Racing Point",
        position: 11,
        wins: 0,
        podiums: 2,
        points: 75,
      },
      {
        year: 2019,
        team: "Racing Point",
        position: 15,
        wins: 0,
        podiums: 0,
        points: 21,
      },
      {
        year: 2018,
        team: "Williams",
        position: 18,
        wins: 0,
        podiums: 0,
        points: 6,
      },
      {
        year: 2017,
        team: "Williams",
        position: 12,
        wins: 0,
        podiums: 1,
        points: 40,
      },
    ],
  },
  {
    firstName: "Pierre",
    lastName: "Gasly",
    number: 10,
    nationality: "French",
    dateOfBirth: "1996-02-07",
    teamName: "Alpine",
    worldChampionships: 0,
    totalRaceWins: 1,
    totalPodiums: 5,
    totalPoints: 394,
    seasonsActive: "2017-present",
    biography:
      "Pierre Gasly is a French racing driver competing for Alpine in Formula One. He won the 2020 Italian Grand Prix in a memorable race and has shown consistent improvement throughout his career.",
    history: [
      {
        year: 2024,
        team: "Alpine",
        position: 14,
        wins: 0,
        podiums: 0,
        points: 16,
      },
      {
        year: 2023,
        team: "Alpine",
        position: 11,
        wins: 0,
        podiums: 0,
        points: 62,
      },
      {
        year: 2022,
        team: "AlphaTauri",
        position: 14,
        wins: 0,
        podiums: 0,
        points: 23,
      },
      {
        year: 2021,
        team: "AlphaTauri",
        position: 9,
        wins: 0,
        podiums: 0,
        points: 110,
      },
      {
        year: 2020,
        team: "AlphaTauri",
        position: 10,
        wins: 1,
        podiums: 1,
        points: 75,
      },
      {
        year: 2019,
        team: "Red Bull/Toro Rosso",
        position: 7,
        wins: 0,
        podiums: 1,
        points: 95,
      },
    ],
  },
  {
    firstName: "Jack",
    lastName: "Doohan",
    number: 7,
    nationality: "Australian",
    dateOfBirth: "2003-01-20",
    teamName: "Alpine",
    worldChampionships: 0,
    totalRaceWins: 0,
    totalPodiums: 0,
    totalPoints: 0,
    seasonsActive: "2025-present",
    biography:
      "Jack Doohan is an Australian racing driver competing for Alpine in Formula One. Son of motorcycle legend Mick Doohan, he graduated from the Alpine Academy to secure an F1 seat.",
    history: [],
  },
  {
    firstName: "Alexander",
    lastName: "Albon",
    number: 23,
    nationality: "Thai-British",
    dateOfBirth: "1996-03-23",
    teamName: "Williams",
    worldChampionships: 0,
    totalRaceWins: 0,
    totalPodiums: 2,
    totalPoints: 232,
    seasonsActive: "2019-2020, 2022-present",
    biography:
      "Alexander Albon is a Thai-British racing driver competing for Williams in Formula One. After a turbulent stint at Red Bull, he rebuilt his career impressively at Williams.",
    history: [
      {
        year: 2024,
        team: "Williams",
        position: 12,
        wins: 0,
        podiums: 0,
        points: 28,
      },
      {
        year: 2023,
        team: "Williams",
        position: 14,
        wins: 0,
        podiums: 0,
        points: 27,
      },
      {
        year: 2022,
        team: "Williams",
        position: 19,
        wins: 0,
        podiums: 0,
        points: 4,
      },
      {
        year: 2020,
        team: "Red Bull Racing",
        position: 7,
        wins: 0,
        podiums: 2,
        points: 105,
      },
      {
        year: 2019,
        team: "Toro Rosso/Red Bull",
        position: 8,
        wins: 0,
        podiums: 0,
        points: 92,
      },
    ],
  },
  {
    firstName: "Carlos",
    lastName: "Sainz",
    number: 55,
    nationality: "Spanish",
    dateOfBirth: "1994-09-01",
    teamName: "Williams",
    worldChampionships: 0,
    totalRaceWins: 4,
    totalPodiums: 25,
    totalPoints: 1150,
    seasonsActive: "2015-present",
    biography:
      "Carlos Sainz Vázquez de Castro is a Spanish racing driver competing for Williams. Son of rally legend Carlos Sainz Sr., he has won multiple races and proven himself as a consistent top performer.",
    history: [
      {
        year: 2024,
        team: "Ferrari",
        position: 5,
        wins: 2,
        podiums: 9,
        points: 290,
      },
      {
        year: 2023,
        team: "Ferrari",
        position: 6,
        wins: 1,
        podiums: 5,
        points: 200,
      },
      {
        year: 2022,
        team: "Ferrari",
        position: 5,
        wins: 1,
        podiums: 9,
        points: 246,
      },
      {
        year: 2021,
        team: "Ferrari",
        position: 5,
        wins: 0,
        podiums: 4,
        points: 164.5,
      },
      {
        year: 2020,
        team: "McLaren",
        position: 6,
        wins: 0,
        podiums: 2,
        points: 105,
      },
      {
        year: 2019,
        team: "McLaren",
        position: 6,
        wins: 0,
        podiums: 1,
        points: 96,
      },
      {
        year: 2018,
        team: "Renault",
        position: 10,
        wins: 0,
        podiums: 0,
        points: 53,
      },
      {
        year: 2017,
        team: "Toro Rosso/Renault",
        position: 9,
        wins: 0,
        podiums: 0,
        points: 54,
      },
      {
        year: 2016,
        team: "Toro Rosso",
        position: 12,
        wins: 0,
        podiums: 0,
        points: 46,
      },
    ],
  },
  {
    firstName: "Yuki",
    lastName: "Tsunoda",
    number: 22,
    nationality: "Japanese",
    dateOfBirth: "2000-05-11",
    teamName: "RB",
    worldChampionships: 0,
    totalRaceWins: 0,
    totalPodiums: 0,
    totalPoints: 115,
    seasonsActive: "2021-present",
    biography:
      "Yuki Tsunoda is a Japanese racing driver competing for RB in Formula One. Known for his fiery personality and impressive pace, he has steadily improved each season.",
    history: [
      { year: 2024, team: "RB", position: 8, wins: 0, podiums: 0, points: 30 },
      {
        year: 2023,
        team: "AlphaTauri",
        position: 13,
        wins: 0,
        podiums: 0,
        points: 17,
      },
      {
        year: 2022,
        team: "AlphaTauri",
        position: 17,
        wins: 0,
        podiums: 0,
        points: 12,
      },
      {
        year: 2021,
        team: "AlphaTauri",
        position: 14,
        wins: 0,
        podiums: 0,
        points: 32,
      },
    ],
  },
  {
    firstName: "Isack",
    lastName: "Hadjar",
    number: 6,
    nationality: "French-Algerian",
    dateOfBirth: "2004-09-28",
    teamName: "RB",
    worldChampionships: 0,
    totalRaceWins: 0,
    totalPodiums: 0,
    totalPoints: 0,
    seasonsActive: "2025-present",
    biography:
      "Isack Hadjar is a French-Algerian racing driver who joined RB for 2025. A Red Bull junior driver and F2 frontrunner, he brings exciting potential to the team.",
    history: [],
  },
  {
    firstName: "Nico",
    lastName: "Hulkenberg",
    number: 27,
    nationality: "German",
    dateOfBirth: "1987-08-19",
    teamName: "Kick Sauber",
    worldChampionships: 0,
    totalRaceWins: 0,
    totalPodiums: 0,
    totalPoints: 530,
    seasonsActive: "2010-2019, 2023-present",
    biography:
      "Nico Hulkenberg is a German racing driver competing for Kick Sauber (future Audi team) in Formula One. Despite never reaching the podium in a record number of starts, he is highly respected for his raw speed.",
    history: [
      {
        year: 2024,
        team: "Haas",
        position: 10,
        wins: 0,
        podiums: 0,
        points: 41,
      },
      {
        year: 2023,
        team: "Haas",
        position: 12,
        wins: 0,
        podiums: 0,
        points: 9,
      },
      {
        year: 2019,
        team: "Renault",
        position: 14,
        wins: 0,
        podiums: 0,
        points: 37,
      },
      {
        year: 2018,
        team: "Renault",
        position: 7,
        wins: 0,
        podiums: 0,
        points: 69,
      },
      {
        year: 2017,
        team: "Renault",
        position: 10,
        wins: 0,
        podiums: 0,
        points: 43,
      },
      {
        year: 2016,
        team: "Force India",
        position: 9,
        wins: 0,
        podiums: 0,
        points: 72,
      },
    ],
  },
  {
    firstName: "Gabriel",
    lastName: "Bortoleto",
    number: 5,
    nationality: "Brazilian",
    dateOfBirth: "2004-10-14",
    teamName: "Kick Sauber",
    worldChampionships: 0,
    totalRaceWins: 0,
    totalPodiums: 0,
    totalPoints: 0,
    seasonsActive: "2025-present",
    biography:
      "Gabriel Bortoleto is a Brazilian racing driver who joined Kick Sauber for 2025. The F3 and F2 champion is considered one of the brightest young talents to enter Formula One.",
    history: [],
  },
  {
    firstName: "Esteban",
    lastName: "Ocon",
    number: 31,
    nationality: "French",
    dateOfBirth: "1996-09-17",
    teamName: "Haas",
    worldChampionships: 0,
    totalRaceWins: 1,
    totalPodiums: 4,
    totalPoints: 432,
    seasonsActive: "2016-present",
    biography:
      "Esteban Ocon is a French racing driver competing for Haas in Formula One. He won the 2021 Hungarian Grand Prix and is known for his determined racing style.",
    history: [
      {
        year: 2024,
        team: "Alpine",
        position: 15,
        wins: 0,
        podiums: 0,
        points: 23,
      },
      {
        year: 2023,
        team: "Alpine",
        position: 12,
        wins: 0,
        podiums: 0,
        points: 58,
      },
      {
        year: 2022,
        team: "Alpine",
        position: 8,
        wins: 0,
        podiums: 0,
        points: 92,
      },
      {
        year: 2021,
        team: "Alpine",
        position: 11,
        wins: 1,
        podiums: 1,
        points: 74,
      },
      {
        year: 2020,
        team: "Renault",
        position: 12,
        wins: 0,
        podiums: 1,
        points: 62,
      },
      {
        year: 2019,
        team: "Did not race",
        position: 0,
        wins: 0,
        podiums: 0,
        points: 0,
      },
      {
        year: 2018,
        team: "Force India",
        position: 12,
        wins: 0,
        podiums: 0,
        points: 49,
      },
      {
        year: 2017,
        team: "Force India",
        position: 8,
        wins: 0,
        podiums: 1,
        points: 87,
      },
    ],
  },
  {
    firstName: "Oliver",
    lastName: "Bearman",
    number: 87,
    nationality: "British",
    dateOfBirth: "2005-05-08",
    teamName: "Haas",
    worldChampionships: 0,
    totalRaceWins: 0,
    totalPodiums: 0,
    totalPoints: 7,
    seasonsActive: "2024-present",
    biography:
      "Oliver Bearman is a British racing driver competing for Haas in Formula One. He made a stunning debut as a substitute at the 2024 Saudi Arabian GP for Ferrari, scoring points on his first outing.",
    history: [
      {
        year: 2024,
        team: "Ferrari/Haas (sub)",
        position: 0,
        wins: 0,
        podiums: 0,
        points: 7,
      },
    ],
  },
];

// ========== RACE HISTORY 2016-2024 ==========
const raceHistoryData = [
  {
    year: 2016,
    totalRaces: 21,
    champion: "Nico Rosberg",
    championTeam: "Mercedes",
    constructorChampion: "Mercedes",
    teamWins: [
      { team: "Mercedes", wins: 19, color: "#00D2BE" },
      { team: "Red Bull Racing", wins: 2, color: "#3671C6" },
      { team: "Ferrari", wins: 0, color: "#E8002D" },
      { team: "Williams", wins: 0, color: "#FFFFFF" },
      { team: "McLaren", wins: 0, color: "#FF8000" },
    ],
  },
  {
    year: 2017,
    totalRaces: 20,
    champion: "Lewis Hamilton",
    championTeam: "Mercedes",
    constructorChampion: "Mercedes",
    teamWins: [
      { team: "Mercedes", wins: 12, color: "#00D2BE" },
      { team: "Ferrari", wins: 5, color: "#E8002D" },
      { team: "Red Bull Racing", wins: 3, color: "#3671C6" },
      { team: "McLaren", wins: 0, color: "#FF8000" },
      { team: "Williams", wins: 0, color: "#FFFFFF" },
    ],
  },
  {
    year: 2018,
    totalRaces: 21,
    champion: "Lewis Hamilton",
    championTeam: "Mercedes",
    constructorChampion: "Mercedes",
    teamWins: [
      { team: "Mercedes", wins: 11, color: "#00D2BE" },
      { team: "Ferrari", wins: 6, color: "#E8002D" },
      { team: "Red Bull Racing", wins: 4, color: "#3671C6" },
      { team: "McLaren", wins: 0, color: "#FF8000" },
      { team: "Renault", wins: 0, color: "#FFF500" },
    ],
  },
  {
    year: 2019,
    totalRaces: 21,
    champion: "Lewis Hamilton",
    championTeam: "Mercedes",
    constructorChampion: "Mercedes",
    teamWins: [
      { team: "Mercedes", wins: 15, color: "#00D2BE" },
      { team: "Ferrari", wins: 3, color: "#E8002D" },
      { team: "Red Bull Racing", wins: 3, color: "#3671C6" },
      { team: "McLaren", wins: 0, color: "#FF8000" },
      { team: "Renault", wins: 0, color: "#FFF500" },
    ],
  },
  {
    year: 2020,
    totalRaces: 17,
    champion: "Lewis Hamilton",
    championTeam: "Mercedes",
    constructorChampion: "Mercedes",
    teamWins: [
      { team: "Mercedes", wins: 13, color: "#00D2BE" },
      { team: "Red Bull Racing", wins: 2, color: "#3671C6" },
      { team: "AlphaTauri", wins: 1, color: "#4E7C9B" },
      { team: "Racing Point", wins: 1, color: "#F596C8" },
      { team: "Ferrari", wins: 0, color: "#E8002D" },
    ],
  },
  {
    year: 2021,
    totalRaces: 22,
    champion: "Max Verstappen",
    championTeam: "Red Bull Racing",
    constructorChampion: "Mercedes",
    teamWins: [
      { team: "Red Bull Racing", wins: 11, color: "#3671C6" },
      { team: "Mercedes", wins: 9, color: "#00D2BE" },
      { team: "Alpine", wins: 1, color: "#FF87BC" },
      { team: "McLaren", wins: 1, color: "#FF8000" },
      { team: "Ferrari", wins: 0, color: "#E8002D" },
    ],
  },
  {
    year: 2022,
    totalRaces: 22,
    champion: "Max Verstappen",
    championTeam: "Red Bull Racing",
    constructorChampion: "Red Bull Racing",
    teamWins: [
      { team: "Red Bull Racing", wins: 17, color: "#3671C6" },
      { team: "Ferrari", wins: 4, color: "#E8002D" },
      { team: "Mercedes", wins: 1, color: "#00D2BE" },
      { team: "McLaren", wins: 0, color: "#FF8000" },
      { team: "Alpine", wins: 0, color: "#FF87BC" },
    ],
  },
  {
    year: 2023,
    totalRaces: 23,
    champion: "Max Verstappen",
    championTeam: "Red Bull Racing",
    constructorChampion: "Red Bull Racing",
    teamWins: [
      { team: "Red Bull Racing", wins: 21, color: "#3671C6" },
      { team: "Ferrari", wins: 1, color: "#E8002D" },
      { team: "McLaren", wins: 1, color: "#FF8000" },
      { team: "Mercedes", wins: 0, color: "#00D2BE" },
      { team: "Alpine", wins: 0, color: "#FF87BC" },
    ],
  },
  {
    year: 2024,
    totalRaces: 24,
    champion: "Max Verstappen",
    championTeam: "Red Bull Racing",
    constructorChampion: "McLaren",
    teamWins: [
      { team: "Red Bull Racing", wins: 9, color: "#3671C6" },
      { team: "McLaren", wins: 7, color: "#FF8000" },
      { team: "Ferrari", wins: 5, color: "#E8002D" },
      { team: "Mercedes", wins: 3, color: "#00D2BE" },
      { team: "Alpine", wins: 0, color: "#FF87BC" },
    ],
  },
];

// ========== UPCOMING RACES 2026 ==========
const racesData = [
  {
    name: "Australian Grand Prix",
    circuit: "Albert Park Circuit",
    country: "Australia",
    city: "Melbourne",
    date: "2026-03-15",
    season: 2026,
    round: 1,
    laps: 58,
    circuitLength: "5.278 km",
    status: "upcoming",
  },
  {
    name: "Chinese Grand Prix",
    circuit: "Shanghai International Circuit",
    country: "China",
    city: "Shanghai",
    date: "2026-03-29",
    season: 2026,
    round: 2,
    laps: 56,
    circuitLength: "5.451 km",
    status: "upcoming",
  },
  {
    name: "Bahrain Grand Prix",
    circuit: "Bahrain International Circuit",
    country: "Bahrain",
    city: "Sakhir",
    date: "2026-04-12",
    season: 2026,
    round: 3,
    laps: 57,
    circuitLength: "5.412 km",
    status: "upcoming",
  },
  {
    name: "Saudi Arabian Grand Prix",
    circuit: "Jeddah Corniche Circuit",
    country: "Saudi Arabia",
    city: "Jeddah",
    date: "2026-04-19",
    season: 2026,
    round: 4,
    laps: 50,
    circuitLength: "6.174 km",
    status: "upcoming",
  },
  {
    name: "Japanese Grand Prix",
    circuit: "Suzuka International Racing Course",
    country: "Japan",
    city: "Suzuka",
    date: "2026-05-03",
    season: 2026,
    round: 5,
    laps: 53,
    circuitLength: "5.807 km",
    status: "upcoming",
  },
  {
    name: "Miami Grand Prix",
    circuit: "Miami International Autodrome",
    country: "United States",
    city: "Miami",
    date: "2026-05-17",
    season: 2026,
    round: 6,
    laps: 57,
    circuitLength: "5.412 km",
    status: "upcoming",
  },
  {
    name: "Emilia Romagna Grand Prix",
    circuit: "Autodromo Enzo e Dino Ferrari",
    country: "Italy",
    city: "Imola",
    date: "2026-05-31",
    season: 2026,
    round: 7,
    laps: 63,
    circuitLength: "4.909 km",
    status: "upcoming",
  },
  {
    name: "Monaco Grand Prix",
    circuit: "Circuit de Monaco",
    country: "Monaco",
    city: "Monte Carlo",
    date: "2026-06-07",
    season: 2026,
    round: 8,
    laps: 78,
    circuitLength: "3.337 km",
    status: "upcoming",
  },
  {
    name: "Spanish Grand Prix",
    circuit: "Circuit de Barcelona-Catalunya",
    country: "Spain",
    city: "Barcelona",
    date: "2026-06-21",
    season: 2026,
    round: 9,
    laps: 66,
    circuitLength: "4.675 km",
    status: "upcoming",
  },
  {
    name: "Canadian Grand Prix",
    circuit: "Circuit Gilles Villeneuve",
    country: "Canada",
    city: "Montreal",
    date: "2026-06-28",
    season: 2026,
    round: 10,
    laps: 70,
    circuitLength: "4.361 km",
    status: "upcoming",
  },
  {
    name: "Austrian Grand Prix",
    circuit: "Red Bull Ring",
    country: "Austria",
    city: "Spielberg",
    date: "2026-07-05",
    season: 2026,
    round: 11,
    laps: 71,
    circuitLength: "4.318 km",
    status: "upcoming",
  },
  {
    name: "British Grand Prix",
    circuit: "Silverstone Circuit",
    country: "United Kingdom",
    city: "Silverstone",
    date: "2026-07-19",
    season: 2026,
    round: 12,
    laps: 52,
    circuitLength: "5.891 km",
    status: "upcoming",
  },
  {
    name: "Belgian Grand Prix",
    circuit: "Circuit de Spa-Francorchamps",
    country: "Belgium",
    city: "Spa",
    date: "2026-07-26",
    season: 2026,
    round: 13,
    laps: 44,
    circuitLength: "7.004 km",
    status: "upcoming",
  },
  {
    name: "Hungarian Grand Prix",
    circuit: "Hungaroring",
    country: "Hungary",
    city: "Budapest",
    date: "2026-08-02",
    season: 2026,
    round: 14,
    laps: 70,
    circuitLength: "4.381 km",
    status: "upcoming",
  },
  {
    name: "Dutch Grand Prix",
    circuit: "Circuit Zandvoort",
    country: "Netherlands",
    city: "Zandvoort",
    date: "2026-08-30",
    season: 2026,
    round: 15,
    laps: 72,
    circuitLength: "4.259 km",
    status: "upcoming",
  },
  {
    name: "Italian Grand Prix",
    circuit: "Autodromo Nazionale Monza",
    country: "Italy",
    city: "Monza",
    date: "2026-09-06",
    season: 2026,
    round: 16,
    laps: 53,
    circuitLength: "5.793 km",
    status: "upcoming",
  },
  {
    name: "Azerbaijan Grand Prix",
    circuit: "Baku City Circuit",
    country: "Azerbaijan",
    city: "Baku",
    date: "2026-09-20",
    season: 2026,
    round: 17,
    laps: 51,
    circuitLength: "6.003 km",
    status: "upcoming",
  },
  {
    name: "Singapore Grand Prix",
    circuit: "Marina Bay Street Circuit",
    country: "Singapore",
    city: "Singapore",
    date: "2026-10-04",
    season: 2026,
    round: 18,
    laps: 62,
    circuitLength: "4.940 km",
    status: "upcoming",
  },
  {
    name: "United States Grand Prix",
    circuit: "Circuit of the Americas",
    country: "United States",
    city: "Austin",
    date: "2026-10-18",
    season: 2026,
    round: 19,
    laps: 56,
    circuitLength: "5.513 km",
    status: "upcoming",
  },
  {
    name: "Mexico City Grand Prix",
    circuit: "Autódromo Hermanos Rodríguez",
    country: "Mexico",
    city: "Mexico City",
    date: "2026-10-25",
    season: 2026,
    round: 20,
    laps: 71,
    circuitLength: "4.304 km",
    status: "upcoming",
  },
  {
    name: "Brazilian Grand Prix",
    circuit: "Autódromo José Carlos Pace",
    country: "Brazil",
    city: "São Paulo",
    date: "2026-11-08",
    season: 2026,
    round: 21,
    laps: 71,
    circuitLength: "4.309 km",
    status: "upcoming",
  },
  {
    name: "Las Vegas Grand Prix",
    circuit: "Las Vegas Strip Circuit",
    country: "United States",
    city: "Las Vegas",
    date: "2026-11-22",
    season: 2026,
    round: 22,
    laps: 50,
    circuitLength: "6.201 km",
    status: "upcoming",
  },
  {
    name: "Qatar Grand Prix",
    circuit: "Lusail International Circuit",
    country: "Qatar",
    city: "Lusail",
    date: "2026-11-29",
    season: 2026,
    round: 23,
    laps: 57,
    circuitLength: "5.419 km",
    status: "upcoming",
  },
  {
    name: "Abu Dhabi Grand Prix",
    circuit: "Yas Marina Circuit",
    country: "UAE",
    city: "Abu Dhabi",
    date: "2026-12-06",
    season: 2026,
    round: 24,
    laps: 58,
    circuitLength: "5.281 km",
    status: "upcoming",
  },
];

// ========== CHAMPIONSHIP STANDINGS 2024 ==========
const standingsData = [
  // Driver Standings 2024
  {
    season: 2024,
    type: "driver",
    position: 1,
    name: "Max Verstappen",
    team: "Red Bull Racing",
    nationality: "Dutch",
    points: 437,
    wins: 9,
  },
  {
    season: 2024,
    type: "driver",
    position: 2,
    name: "Lando Norris",
    team: "McLaren",
    nationality: "British",
    points: 374,
    wins: 4,
  },
  {
    season: 2024,
    type: "driver",
    position: 3,
    name: "Charles Leclerc",
    team: "Ferrari",
    nationality: "Monegasque",
    points: 356,
    wins: 3,
  },
  {
    season: 2024,
    type: "driver",
    position: 4,
    name: "Oscar Piastri",
    team: "McLaren",
    nationality: "Australian",
    points: 292,
    wins: 2,
  },
  {
    season: 2024,
    type: "driver",
    position: 5,
    name: "Carlos Sainz",
    team: "Ferrari",
    nationality: "Spanish",
    points: 290,
    wins: 2,
  },
  {
    season: 2024,
    type: "driver",
    position: 6,
    name: "George Russell",
    team: "Mercedes",
    nationality: "British",
    points: 245,
    wins: 2,
  },
  {
    season: 2024,
    type: "driver",
    position: 7,
    name: "Lewis Hamilton",
    team: "Mercedes",
    nationality: "British",
    points: 211,
    wins: 2,
  },
  {
    season: 2024,
    type: "driver",
    position: 8,
    name: "Sergio Perez",
    team: "Red Bull Racing",
    nationality: "Mexican",
    points: 152,
    wins: 0,
  },
  {
    season: 2024,
    type: "driver",
    position: 9,
    name: "Fernando Alonso",
    team: "Aston Martin",
    nationality: "Spanish",
    points: 70,
    wins: 0,
  },
  {
    season: 2024,
    type: "driver",
    position: 10,
    name: "Nico Hulkenberg",
    team: "Haas",
    nationality: "German",
    points: 41,
    wins: 0,
  },
  // Constructor Standings 2024
  {
    season: 2024,
    type: "constructor",
    position: 1,
    name: "McLaren",
    nationality: "British",
    points: 666,
    wins: 6,
  },
  {
    season: 2024,
    type: "constructor",
    position: 2,
    name: "Ferrari",
    nationality: "Italian",
    points: 652,
    wins: 5,
  },
  {
    season: 2024,
    type: "constructor",
    position: 3,
    name: "Red Bull Racing",
    nationality: "Austrian",
    points: 589,
    wins: 9,
  },
  {
    season: 2024,
    type: "constructor",
    position: 4,
    name: "Mercedes",
    nationality: "German",
    points: 468,
    wins: 4,
  },
  {
    season: 2024,
    type: "constructor",
    position: 5,
    name: "Aston Martin",
    nationality: "British",
    points: 94,
    wins: 0,
  },
  {
    season: 2024,
    type: "constructor",
    position: 6,
    name: "Haas",
    nationality: "American",
    points: 58,
    wins: 0,
  },
  {
    season: 2024,
    type: "constructor",
    position: 7,
    name: "RB",
    nationality: "Italian",
    points: 46,
    wins: 0,
  },
  {
    season: 2024,
    type: "constructor",
    position: 8,
    name: "Williams",
    nationality: "British",
    points: 17,
    wins: 0,
  },
  {
    season: 2024,
    type: "constructor",
    position: 9,
    name: "Alpine",
    nationality: "French",
    points: 16,
    wins: 0,
  },
  {
    season: 2024,
    type: "constructor",
    position: 10,
    name: "Kick Sauber",
    nationality: "Swiss",
    points: 0,
    wins: 0,
  },
];

// ========== TEAM STAFF ==========
const teamStaffData = [
  // Red Bull Racing
  {
    name: "Ben Waterhouse",
    role: "Chief Mechanic",
    department: "mechanical",
    teamName: "Red Bull Racing",
    experience: "15 years",
    nationality: "British",
  },
  {
    name: "Paul Monaghan",
    role: "Chief Engineer",
    department: "mechanical",
    teamName: "Red Bull Racing",
    experience: "20 years",
    nationality: "British",
  },
  {
    name: "Simon Rennie",
    role: "Race Engineer",
    department: "strategy",
    teamName: "Red Bull Racing",
    experience: "18 years",
    nationality: "British",
  },
  {
    name: "Gianpiero Lambiase",
    role: "Performance Engineer",
    department: "strategy",
    teamName: "Red Bull Racing",
    experience: "16 years",
    nationality: "Italian",
  },
  {
    name: "Lee Stevenson",
    role: "Crew Chief - Pitstop",
    department: "pitstop",
    teamName: "Red Bull Racing",
    experience: "12 years",
    nationality: "British",
  },
  {
    name: "Tom Wood",
    role: "Physical Trainer",
    department: "physical",
    teamName: "Red Bull Racing",
    experience: "10 years",
    nationality: "British",
  },
  // Mercedes
  {
    name: "Matthew Deane",
    role: "Chief Mechanic",
    department: "mechanical",
    teamName: "Mercedes",
    experience: "14 years",
    nationality: "British",
  },
  {
    name: "Andrew Shovlin",
    role: "Trackside Engineering Director",
    department: "strategy",
    teamName: "Mercedes",
    experience: "22 years",
    nationality: "British",
  },
  {
    name: "Marcus Dudley",
    role: "Race Engineer",
    department: "strategy",
    teamName: "Mercedes",
    experience: "12 years",
    nationality: "British",
  },
  {
    name: "Jon Neal",
    role: "Crew Chief - Pitstop",
    department: "pitstop",
    teamName: "Mercedes",
    experience: "11 years",
    nationality: "British",
  },
  {
    name: "Angela Cullen",
    role: "Physical Trainer",
    department: "physical",
    teamName: "Mercedes",
    experience: "8 years",
    nationality: "New Zealander",
  },
  // Ferrari
  {
    name: "Diego Ioverno",
    role: "Sporting Director",
    department: "management",
    teamName: "Ferrari",
    experience: "20 years",
    nationality: "Italian",
  },
  {
    name: "Matteo Togninalli",
    role: "Head of Track Engineering",
    department: "mechanical",
    teamName: "Ferrari",
    experience: "18 years",
    nationality: "Italian",
  },
  {
    name: "Bryan Bozzi",
    role: "Race Engineer",
    department: "strategy",
    teamName: "Ferrari",
    experience: "14 years",
    nationality: "Italian",
  },
  {
    name: "Marco Mattioli",
    role: "Crew Chief - Pitstop",
    department: "pitstop",
    teamName: "Ferrari",
    experience: "16 years",
    nationality: "Italian",
  },
  {
    name: "Andrea Ferrari",
    role: "Physical Trainer",
    department: "physical",
    teamName: "Ferrari",
    experience: "9 years",
    nationality: "Italian",
  },
  {
    name: "Enrico Cardile",
    role: "Head of Aerodynamics",
    department: "aerodynamics",
    teamName: "Ferrari",
    experience: "15 years",
    nationality: "Italian",
  },
  // McLaren
  {
    name: "Paul James",
    role: "Team Manager",
    department: "management",
    teamName: "McLaren",
    experience: "20 years",
    nationality: "British",
  },
  {
    name: "Will Joseph",
    role: "Race Engineer",
    department: "strategy",
    teamName: "McLaren",
    experience: "10 years",
    nationality: "British",
  },
  {
    name: "Tom Stallard",
    role: "Race Engineer",
    department: "strategy",
    teamName: "McLaren",
    experience: "15 years",
    nationality: "British",
  },
  {
    name: "Neil Houldey",
    role: "Chief Mechanic",
    department: "mechanical",
    teamName: "McLaren",
    experience: "18 years",
    nationality: "British",
  },
  {
    name: "Mark Temple",
    role: "Crew Chief - Pitstop",
    department: "pitstop",
    teamName: "McLaren",
    experience: "14 years",
    nationality: "British",
  },
  // Aston Martin
  {
    name: "Josh Sherwin",
    role: "Chief Mechanic",
    department: "mechanical",
    teamName: "Aston Martin",
    experience: "12 years",
    nationality: "British",
  },
  {
    name: "Pedro de la Rosa",
    role: "Ambassador & Advisor",
    department: "management",
    teamName: "Aston Martin",
    experience: "25 years",
    nationality: "Spanish",
  },
  {
    name: "Chris Mayberry",
    role: "Crew Chief - Pitstop",
    department: "pitstop",
    teamName: "Aston Martin",
    experience: "10 years",
    nationality: "British",
  },
  {
    name: "Dan Williams",
    role: "Physical Trainer",
    department: "physical",
    teamName: "Aston Martin",
    experience: "8 years",
    nationality: "British",
  },
  // Alpine
  {
    name: "Julian Rouse",
    role: "Sporting Director",
    department: "management",
    teamName: "Alpine",
    experience: "15 years",
    nationality: "British",
  },
  {
    name: "David Sanchez",
    role: "Technical Director",
    department: "aerodynamics",
    teamName: "Alpine",
    experience: "18 years",
    nationality: "French",
  },
  {
    name: "Karel Loos",
    role: "Chief Mechanic",
    department: "mechanical",
    teamName: "Alpine",
    experience: "13 years",
    nationality: "Dutch",
  },
  {
    name: "Matthew Harman",
    role: "Race Engineer",
    department: "strategy",
    teamName: "Alpine",
    experience: "12 years",
    nationality: "British",
  },
  // Haas
  {
    name: "Mark Slade",
    role: "Lead Race Engineer",
    department: "strategy",
    teamName: "Haas",
    experience: "20 years",
    nationality: "British",
  },
  {
    name: "Rico Furchtbar",
    role: "Chief Mechanic",
    department: "mechanical",
    teamName: "Haas",
    experience: "11 years",
    nationality: "German",
  },
  {
    name: "Peter Crolla",
    role: "Head of Trackside Engineering",
    department: "strategy",
    teamName: "Haas",
    experience: "14 years",
    nationality: "British",
  },
  {
    name: "Francesco Nenci",
    role: "Crew Chief - Pitstop",
    department: "pitstop",
    teamName: "Haas",
    experience: "10 years",
    nationality: "Italian",
  },
  // Kick Sauber
  {
    name: "Beat Zehnder",
    role: "Sporting Director",
    department: "management",
    teamName: "Kick Sauber",
    experience: "30 years",
    nationality: "Swiss",
  },
  {
    name: "Xevi Pujolar",
    role: "Head of Trackside Engineering",
    department: "strategy",
    teamName: "Kick Sauber",
    experience: "19 years",
    nationality: "Spanish",
  },
  {
    name: "Marco Calamassi",
    role: "Chief Mechanic",
    department: "mechanical",
    teamName: "Kick Sauber",
    experience: "12 years",
    nationality: "Italian",
  },
  {
    name: "Alessandro Alunni Bravi",
    role: "Team Representative",
    department: "management",
    teamName: "Kick Sauber",
    experience: "16 years",
    nationality: "Italian",
  },
  // RB
  {
    name: "Alan Permane",
    role: "Racing Director",
    department: "management",
    teamName: "RB",
    experience: "34 years",
    nationality: "British",
  },
  {
    name: "Jonathan Eddolls",
    role: "Chief Race Engineer",
    department: "strategy",
    teamName: "RB",
    experience: "17 years",
    nationality: "British",
  },
  {
    name: "Guillaume Dezoteux",
    role: "Head of Vehicle Performance",
    department: "aerodynamics",
    teamName: "RB",
    experience: "14 years",
    nationality: "French",
  },
  {
    name: "Ernesto Desiderio",
    role: "Chief Mechanic",
    department: "mechanical",
    teamName: "RB",
    experience: "13 years",
    nationality: "Italian",
  },
  // Williams
  {
    name: "Sven Smeets",
    role: "Sporting Director",
    department: "management",
    teamName: "Williams",
    experience: "19 years",
    nationality: "Belgian",
  },
  {
    name: "Dave Robson",
    role: "Head of Vehicle Performance",
    department: "strategy",
    teamName: "Williams",
    experience: "18 years",
    nationality: "British",
  },
  {
    name: "Gaetan Jego",
    role: "Chief Mechanic",
    department: "mechanical",
    teamName: "Williams",
    experience: "12 years",
    nationality: "French",
  },
  {
    name: "Luke Browning",
    role: "Physical Trainer",
    department: "physical",
    teamName: "Williams",
    experience: "7 years",
    nationality: "British",
  },
];

// ========== SEED FUNCTION ==========
const seedDB = async () => {
  try {
    await connectDB();
    console.log("Clearing existing data...");

    await User.deleteMany({});
    await Team.deleteMany({});
    await Driver.deleteMany({});
    await Race.deleteMany({});
    await Standing.deleteMany({});
    await TeamStaff.deleteMany({});
    await RaceHistory.deleteMany({});

    // Create admin and user
    console.log("Creating users...");
    await User.create({
      username: "admin",
      email: "admin@f1management.com",
      password: "admin123",
      role: "admin",
    });
    await User.create({
      username: "user",
      email: "user@f1management.com",
      password: "user123",
      role: "user",
    });

    // Create teams
    console.log("Creating teams...");
    const teams = await Team.insertMany(teamsData);
    const teamMap = {};
    teams.forEach((t) => {
      teamMap[t.name] = t._id;
    });

    // Create drivers with team references
    console.log("Creating drivers...");
    const driversToInsert = driversData.map((d) => ({
      ...d,
      team: teamMap[d.teamName],
      teamName: undefined,
    }));
    // Remove teamName from each
    driversToInsert.forEach((d) => delete d.teamName);
    // Need to set team properly
    const driverDocs = [];
    for (const d of driversData) {
      const doc = { ...d, team: teamMap[d.teamName] };
      delete doc.teamName;
      driverDocs.push(doc);
    }
    await Driver.insertMany(driverDocs);

    // Create races
    console.log("Creating races...");
    await Race.insertMany(racesData);

    // Create standings
    console.log("Creating standings...");
    await Standing.insertMany(standingsData);

    // Create team staff with team references
    console.log("Creating team staff...");
    const staffDocs = teamStaffData.map((s) => ({
      ...s,
      team: teamMap[s.teamName],
    }));
    await TeamStaff.insertMany(staffDocs);

    // Create race history
    console.log("Creating race history...");
    await RaceHistory.insertMany(raceHistoryData);

    console.log("Database seeded successfully!");
    console.log("Admin: admin@f1management.com / admin123");
    console.log("User: user@f1management.com / user123");

    process.exit(0);
  } catch (error) {
    console.error("Seeding error:", error);
    process.exit(1);
  }
};

seedDB();
